### ISSUE TITLE
Display characters in order of appearance

### ISSUE THREAD

**Issue by lehkost** [dracor-org/dracor-frontend#1]
Right now, characters are displayed as they appear in the ```<particDesc>``` section. The long-term goal is to sort them there by order of appearance as well, but could we make the character list on the website dependent strictly on the order of appearance of characters in the ```<body>``` part?

**Comment by cmil** [comment]
In https://github.com/dracor-org/dracor-exist/commit/79dc0f7d534d4e20a2d0e39251de540d7847ac32 we changed how the list of characters is extracted. They should now be listed in order of appearance.
