### ISSUE TITLE
Display Wikidata P18 image per author

### ISSUE THREAD

**Issue by lehkost** [dracor-org/dracor-frontend#10]
If unavailable, use dummy silhouettes from [here](https://dlina.github.io/The-Facebook-of-German-Playwrights/).

**Comment by cmil** [comment]
Where would we best display those images?

**Comment by lehkost** [comment]
hm, given the current design, we could place them left of the author/title/subtitle info, in thumbnail format with fixed height? and maybe make it clickable so the link leads to the image on wikimedia commons?
