### ISSUE TITLE
Fix Headroom glitches

### ISSUE THREAD

**Issue by cmil** [dracor-org/dracor-frontend#109]
There is a glitch apparently caused by headroom. When scrolling up on the start page, the top of the first card is hidden underneath the navbar and only after some delay fully reveals. This is especially noticeable on mobile browsers but can be seen on desktop browsers too.

![dracor-capture](https://user-images.githubusercontent.com/3439037/95600882-06f1b800-0a53-11eb-9dd1-4e81f961a297.gif)

_Originally posted by @cmil in https://github.com/dracor-org/dracor-frontend/pull/99#discussion_r502502937_

**Comment by cmil** [comment]
A fix for this may also obsolete a workaround described here: https://github.com/dracor-org/dracor-frontend/pull/100#discussion_r528681936.

**Comment by lehkost** [comment]
Experiencing the same effect on Firefox @ Android.
