### ISSUE TITLE
Update site navigation

### ISSUE THREAD

**Issue by cmil** [dracor-org/dracor-frontend#111]
The navigation of dracor-frontend 1.0.0 should have the following structure:

- ABOUT
  - What Is DraCor? [doc/what-is-dracor.md]
  - Credits [doc/credits.md]
  - Imprint [doc/imprint-and-gdpr.md]
- CORPORA [List of all corpora]
- TOOLS
  - API
  - SPARQL
  - ezlinavis [➔ https://ezlinavis.dracor.org/]
  - Shiny DraCor [➔ https://shiny.dracor.org/]
- HOW TO
  - Tutorials [doc/tutorials.md]
  - Research [doc/research.md]
- SWAG
  - Merch [doc/merch.md]
  - DraCor Moments [to be added after 1.0.0]

**Comment by cmil** [comment]
Changes are deployed at https://staging.dracor.org. Please review!

**Comment by markschwindt** [comment]
Looks great already! 

I did, however, have noticed that the area around links in dropdowns does not belong to the actual link while indicating (`button type="button"`;`cursor: pointer`) that it should.

<img width="1262" alt="Bildschirmfoto 2020-11-23 um 16 05 27" src="https://user-images.githubusercontent.com/53089225/99978120-d6b56d00-2da5-11eb-832f-ad30b98f0aea.png">

It is barely noticeable in the corpora dropdown but evident in dropdowns with less text.

I would suggest wrapping the link around `DropdownItem` to increase the clickable area.

**Comment by cmil** [comment]
@markschwindt I changed the links so the the entire dropdown item is an effective click target. As a side effect the active page is now highlighted in the dropdowns.

**Comment by markschwindt** [comment]
@cmil That is a good side effect, I think. As far as I'm concerned, the issue can be closed.
