### ISSUE TITLE
Improve citation proposition on frontpage

### ISSUE THREAD

**Issue by lehkost** [dracor-org/dracor-frontend#117]
Could we please revamp the suggestion to cite DraCor like this:

**If you want to cite DraCor, please use the following reference (BibTeX, RIS):**
Fischer, Frank, et al. (2019). Programmable Corpora: Introducing DraCor, an Infrastructure for the Research on European Drama. In *Proceedings of DH2019: "Complexities"*, Utrecht University, doi:[10.5281/zenodo.4284002](https://doi.org/10.5281/zenodo.4284002).

(Note: BibTeX and RIS would have to be links to the corresponding bibliographic records which we would have to put on the DraCor website: ```"cite_dracor.bib"```, ```"cite_dracor.ris"``` – both here attached in a ZIP file: [cite_dracor.zip](https://github.com/dracor-org/dracor-frontend/files/5579845/cite_dracor.zip).)

**Comment by cmil** [comment]
Implemented in PR #118 and deployed to staging.dracor.org.

**Comment by lehkost** [comment]
Thanks! Before closing this issue I'd like to propose to deliver a MIME type that the browser accepts for the BibTex and RIS files, so you don't have to necessarily save the file.

**Comment by cmil** [comment]
This needs to be changed in the server configuration which is why I opened the above issue.
