### ISSUE TITLE
Link API version to complete release history, not only the most recent release

### ISSUE THREAD

**Issue by lehkost** [dracor-org/dracor-frontend#126]
Right now, the footer mentions the current API version DraCor is running on and links to the corresponding release on GitHub ("This site runs on DraCor API 0.73.0" pointing to ```https://github.com/dracor-org/dracor-api/releases/tag/v0.73.0```).

I propose to link **not** to the latest release, but to the whole release history, so everyone interested can get a quick impression of recent releases, so we'd link to ```https://github.com/dracor-org/dracor-api/releases``` instead.

**Comment by cmil** [comment]
The list of all releases would be just another click away. Wouldn't that be easy enough for everyone interested?

<img width="553" alt="image" src="https://user-images.githubusercontent.com/3439037/100605117-bb97af80-3307-11eb-801b-bc497fac2889.png">

Also, in case of pre-releases, casual viewers might get confused by some other version than they clicked on showing up on top of the list.

**Comment by lehkost** [comment]
Ok, convinced. I didn't see the point with pre-releases that could be confusing.
