### ISSUE TITLE
Scrolling of play detail pages broken in (desktop) Safari

### ISSUE THREAD

**Issue by cmil** [dracor-org/dracor-frontend#131]
On play detail pages (e.g. https://dracor.org/ger/lessing-emilia-galotti) in Safari under macOS the transition of the sticky header does not work correctly and prevents the page from being scrolled up completely.

(tested with Safari  14.0.1, macOS 10.15.7)

**Comment by markschwindt** [comment]
Side effect of Headroom deactivation btw.
