### ISSUE TITLE
Document the calculation of normalised year

### ISSUE THREAD

**Issue by lehkost** [dracor-org/dracor-frontend#152]
There is no easily accessible documentation as to how the normalised year is calculated out of the 3 years given, if available (written / print / premiere). The calculation of the normalised year is contingent and should be transparent to the user. It is mainly used to make the chronological plotting of features easier.

The XQuery code for the "formula" we use is located [here](https://github.com/dracor-org/dracor-api/blob/c95af4883f84a43c6ea8324075abd236f0493ffb/modules/util.xqm#L356).

**Comment by cmil** [comment]
This seems to be done with https://staging.dracor.org/doc/faq
