### ISSUE TITLE
Offer Gephi-prone CSV download for each play

### ISSUE THREAD

**Issue by lehkost** [dracor-org/dracor-frontend#16]
Just like in [ezlinavis](https://ezlinavis.dracor.org/). Use type "Undirected" here as well. – These downloads will help to create embellished versions of our graphs…

**Comment by cmil** [comment]
@lehkost Could we just extend the CSV resource we already have (e.g. http https://dracor.org/api/corpus/ger/play/alberti-im-suff/networkdata/csv)? Ivan would probably have to adapt the [dracor-shiny](https://github.com/dracor-org/dracor-shiny) though.

**Comment by lehkost** [comment]
@cmil Good idea, cos after all it is "Undirected" connections we're extracting, so our CSV data set would be more semantic, too… – Another aspect of this ticket was to put up a simple download button on top or to the side of each network so downloading is easier for the end user…

**Comment by cmil** [comment]
In the network modal there is now a download link to the CSV which now also contains the `Type` column. The shiny app seems to work just fine without modification (I just [made the _About..._ update work](https://github.com/dracor-org/dracor-shiny/commit/a0a30bc533434fb7b925229759e01541a2d2ad40) and [adjusted the title](https://github.com/dracor-org/dracor-shiny/commit/349460c4ae277a47037080b175b95bd6522e8a4a) there).
