### ISSUE TITLE
Add Sigma.js functions to network display

### ISSUE THREAD

**Issue by lehkost** [dracor-org/dracor-frontend#169]
Desirable additions to how we use Sigma.js on the DraCor single-play pages:

* <strike>**Zoom in/out** button</strike> --> #137
* <strike>**click on node** shows other nodes directly connected to focal node (distance = 1) (see "Bind callbacks to events" example on [Sigma.js homepage](http://sigmajs.org/))</strike> --> #258
* <strike>relate node size to **word count** of a character (using fixed numbers for min and max node size)</strike> --> #259
* <strike>relate node colour to **gender** information (male, female, unknown)</strike> --> #184
* <strike>Search function for nodes (cf. [here](https://codepen.io/HectorHS/pen/eYmQyYo))</strike> (not for now)
* <strike>Colouring of clusters/communities (cf. [here](https://sigmajs.john-coene.com/reference/cluster.html))</strike> (not now)

**Comment by cmil** [comment]
I think we should create separate issues for the items in the desirable additions list (where isn't one yet, and maybe even for the ones marked with "not now") and close this issue.

**Comment by cmil** [comment]
I created individual issues, closing this one.
