### ISSUE TITLE
Segment count skips scenes without speeches

### ISSUE THREAD

**Issue by lehkost** [dracor-org/dracor-frontend#17]
Example: [**This drama**](https://dracor.org/ger/grabbe-scherz-satire-ironie-und-tiefere-bedeutung) has 14 scenes, cf. [**here**](http://www.zeno.org/Literatur/M/Grabbe,+Christian+Dietrich/Dramen/Scherz,+Satire,+Ironie+und+tiefere+Bedeutung). The segment counter only counts 13 segments, see [**here**](https://dracor.org/api/corpus/ger/play/grabbe-scherz-satire-ironie-und-tiefere-bedeutung/segmentation). The reason seems to be that [**scene III/2**](http://www.zeno.org/Literatur/M/Grabbe,+Christian+Dietrich/Dramen/Scherz,+Satire,+Ironie+und+tiefere+Bedeutung/3.+Akt/2.+Szene) only contains stage directions, no speeches.

Proposed solution: Include "empty" segments in segment count.

**Comment by cmil** [comment]
In the current implementation any `div` containing speeches as direct child elements is considered a segment. To include empty segments we would have to make sure that `div`s are only used to mark segments (which could be a bit fragile) or we would have to find a more robust way to determine segments.

**Comment by lehkost** [comment]
Right, we'll have to find a clever solution that's not complicating things more than it should. 😊 So the current extraction algorithm is working just fine, it should just (additionally) include empty scenes, without involving other, non-scenic ```div```s (which we need, too). Empty scenes only appear in ```<body>``` (not ```front```) **and** have a ```<div type="scene">``` at the beginning, which could be leveraged to recognise "empty" ones (that is, without speakers, only stage directions)… My suggestion would be: Regard all ```div```s as scenes that have an ```<sp>``` in them (just like we do now), plus add empty scenes which are marked as ```<div type="scene">```.

**Comment by cmil** [comment]
This has been fixed and deployed in dracor-exist v0.10.1.
