### ISSUE TITLE
Add direct download button for metadata table per corpus

### ISSUE THREAD

**Issue by lehkost** [dracor-org/dracor-frontend#177]
After implementing a direct download url for the metadata in CSV format (see https://github.com/dracor-org/dracor-api/issues/142), we can link to the metadata in the corpus overviews.

Proposition:

Corpus licensed under […] · Download a comprehensive table with metadata on all plays in the corpus: [JSON](https://dracor.org/api/corpus/ger/metadata) · [CSV](https://dracor.org/api/corpus/ger/metadata/csv).

**Comment by cmil** [comment]
The `/corpora/{corpusname}/metadata/csv` endpoint is now available on staging.
