### ISSUE TITLE
Add clickable Wikidata IDs to characters in Cast list view

### ISSUE THREAD

**Issue by lehkost** [dracor-org/dracor-frontend#178]
After implementing https://github.com/dracor-org/dracor-api/issues/143, we can make use of Wikidata IDs for characters in the frontend ("Network" tab and "Relations" tab).

So, if a Wikidata ID is availabe for a character, it should be shown in the cast list in the right sidebar, right next to the gender symbol, in our usual Wikidata box, and made clickable.

**Comment by cmil** [comment]
This has been resolved with #186.
