### ISSUE TITLE
Corpus card carousel does not render correctly for mobile breakpoint

### ISSUE THREAD

**Issue by cmil** [dracor-org/dracor-frontend#179]
There is a positioning glitch in the corpus card carousel for the mobile breakpoint. While it looks like only half the number of cards is in the carousel, every second card seems to be positioned to the right of its predecessor outside the viewport. The screenshot shows this after disabling `overflow: hidden` on the carousel. 

<img width="497" alt="image" src="https://user-images.githubusercontent.com/3439037/125046162-0cd9ff80-e09e-11eb-9a66-7489fda446aa.png">

**Comment by markschwindt** [comment]
This is most probably caused by the overflow of the nonbreakable text in the footer. Will fix it in one of the upcoming PRs.

**Comment by cmil** [comment]
I think it's caused by the Bootstrap Grid and the react-slick Slider not working well together. I'll push a fix in a bit.

**Comment by cmil** [comment]
Unfortunately the above change does not fix the issue. In my local environment it looked like it did, but actually the issue didn't exist there at all. Apparently it depends on the number of corpora, which is lower in my local database. The problem seems to occur if the number of corpora exceeds 13 and thus most likely only became visible after the addition of `BashDraCor` on staging.
