### ISSUE TITLE
If a work has two or more authors, insert separator in overview and modal window

### ISSUE THREAD

**Issue by lehkost** [dracor-org/dracor-frontend#18]
Example: "Die Familie Selicke".

Could use ```&middot;``` or slash or whatever looks best, like so:

Holz, Arno · Schlaf, Johannes
pnd:118553216 · pnd:118607871

**Comment by cmil** [comment]
Implemented and deployed with v0.7.0 (see https://dracor.org/ger/holz-die-familie-selicke).
