### ISSUE TITLE
Adjust sigma gender representation

### ISSUE THREAD

**Issue by markschwindt** [dracor-org/dracor-frontend#184]
As of the current staged version the character gender representation is being signaled both through gender symbols in the cast list and three different network node colours on the sigma canvas. While offering a more detailed view, the overall implementation could become more intuitive.

**Comment by markschwindt** [comment]
I would suggest to reduce the number of node color variants to only two colours from the palette: `#61affe` for default (undefined/neutral) and `#1f2448` for gendered nodes.

The distinction between male and female characters could in turn be indicated through different node shapes: circle for female and square for male characters. For that latter the sigma component setting would need to change from `<NodeShapes default="circle"/>` to `<NodeShapes default="square"/>`

**Comment by lehkost** [comment]
sounds good, let's try?

**Comment by cmil** [comment]
The above PR implements the changes suggested by @markschwindt. @lehkost please have a look at staging.dracor.org and maybe leave aa comment in the PR when further work is necessary.
