### ISSUE TITLE
Padding missing in author info on Safari (iPad)

### ISSUE THREAD

**Issue by lehkost** [dracor-org/dracor-frontend#190]
There seems to be no distance between the right side of the author image and the left side of the author detail box, as indicates the screenshot below (Safari on iPad).
![dracor-on-ipad-safari](https://user-images.githubusercontent.com/6539515/127111368-a4570de0-7bae-4c9b-8b86-b55b0b333b4c.jpg)

**Comment by markschwindt** [comment]
This is probably due to an outdated browser and/or iOS version not being able to interpret the `gap` declaration. The following PR takes care of that issue by reverting to the standard `margin` declaration.

**Comment by lehkost** [comment]
> This is probably due to an outdated browser and/or iOS version not being able to interpret the `gap` declaration.

I tested on 8th-generation iPad running 14.4.1.

**Comment by lehkost** [comment]
Ok, just updated iPadOS, padding works as supposed on 14.7.1.

(Btw, 14.4.1 was released in March 2021, so 4 months make this difference…)

**Comment by markschwindt** [comment]
Surprisingly it does: [ https://caniuse.com/?search=gap](url)
I'd still suggest to fall back to `margin` just to be safe.
