### ISSUE TITLE
Add placeholder if parts of author information are missing

### ISSUE THREAD

**Issue by lehkost** [dracor-org/dracor-frontend#194]
For example: https://staging.dracor.org/ita/beccari-il-sacrificio-1555

* "b. , Ferrara"

In this case, year of birth is missing. If either years or places of birth/death are missing, we should put a placeholder to make transparent that this info is not available in Wikidata (or not known at all). Could be a question mark "?", or something like "[n/a]".

**Comment by cmil** [comment]
Couldn't we just omit the missing part? So in the example we would display "b. Ferrara". When the birth or death place is missing it would look like "b. 1234". This was the reason I didn't put a comma between year and place in the original implementation. But of course we could omit the comma if only one part of information is available.

**Comment by lehkost** [comment]
Good solution, but what if we have neither date nor location, would this yield an empty "b." line?

**Comment by cmil** [comment]
When there is no information, we'd just omit the b. or d. line.
