### ISSUE TITLE
Introduce diagrams on speech distribution

### ISSUE THREAD

**Issue by lehkost** [dracor-org/dracor-frontend#20]
For the window on the right, two typs of diagrams should be introduced, per play:
1. **Speech distribution (Yarkho style):** x-axis: Monologues, dialogues, polylogues (1 – 2 – 3 – 4 – 5 – etc.); y-axis: number of scenes with monologues, dialogues, polylogues, etc. – cf. [Yarkho 1997](http://rvb.ru/philologica/04/04iarxo.htm):

![yarkho-1997-table-7a](https://user-images.githubusercontent.com/6539515/35856020-c9c9ede4-0b45-11e8-891b-b0d39db71e3a.gif)

2. **Speech distribution (Sapogov style):** x-axis: each scene numbered (1, 2, 3, 4, 5, etc.); y-axis: number of speaking characters per scene – like described in [Sapogov 1974](https://www.zotero.org/groups/940512/dlina/items/itemKey/BU7ZB3LY):

![sapogov-1974-page-63](https://user-images.githubusercontent.com/6539515/35855878-75bc4cb0-0b45-11e8-9175-693fb73e318a.jpg)

**Comment by cmil** [comment]
A first version of the diagrams has now been implemented in PR #25 (and deployed to dracor.org). We still may want to refine the labels and layout.

**Comment by lehkost** [comment]
That was fast, great job! 🌠
As for refinements, what about a headline and labels for x- and y-axes for both diagrams, maybe like this:
* left:
  * headline: Speech distribution (as described in [Sapogov 1974](https://www.zotero.org/groups/940512/dlina/items/itemKey/BU7ZB3LY)) [include link if possible]
  * x-axis: number of scene
  * y-axis: number of characters
* right:
  * headline: Speech distribution (as described in [Yarkho 1997](http://rvb.ru/philologica/04/04iarxo.htm))
  * x-axis: number of characters per scene (monologues, dialogues, polylogues)
  * y-axis: number of scenes

And two suggestions re numbers on axes:
* use only integers on the scale, no 0.5-steps needed
* always start y-axes at zero, not at 1 like [here](https://dracor.org/rus/gogol-zhenitba#speech) (left diagram)

**Comment by lehkost** [comment]
Thanks for the quick implementation.
One last suggestion: In the Yarkho diagram to the right ([example](https://dracor.org/ger/anzengruber-die-kreuzelschreiber#speech)), the x-axis should always start at 1, even if there is no monologue, etc.

**Comment by cmil** [comment]
As far as I can see, with chartjs which we are currently using, we would have to make the x-axis linear, to force it to start with 1. That, however, would add ticks, that do not correspond to actually occurring numbers of speakers, which I don't think would be desirable. For instance, the x-axis for https://dracor.org/ger/alberti-im-suff#speech would contain all integers from 1 through 9.

**Comment by cmil** [comment]
I just added the links mentioned above to PR #25.

**Comment by lehkost** [comment]
I think it's better in general to have linear axes altogether, because they convey a more realistic notion of speech distribution, especially if some values in-between equal zero.

**Comment by cmil** [comment]
I opened a the above issue for the linear axis so we can merge #25 and close this one.
