### ISSUE TITLE
Fix fade overlapping on tablets

### ISSUE THREAD

**Issue by markschwindt** [dracor-org/dracor-frontend#210]

**Comment by cmil** [comment]
The above fix caused a problem with navigation dropdowns being hidden under the `PlayDetailsHeader` (still on Curren staging, e.g. https://staging.dracor.org/ger/gryphius-cardenio-und-celinde), which is why it was reverted for the 1.1.0 release. We need another fix.

**Comment by markschwindt** [comment]
I still can't actually see it, but it is absolutely possible since both elements share the same z-index now. The quick fix below should take care of that for now.

**Comment by cmil** [comment]
@markschwindt see https://github.com/dracor-org/dracor-frontend/pull/214#issuecomment-894241781
