### ISSUE TITLE
Reformat <titlePage> with CETEIcean

### ISSUE THREAD

**Issue by lehkost** [dracor-org/dracor-frontend#233]
We decided to favour full ```<titlePage>``` information per play, like so:

```xml
<titlePage>
  <docTitle>
    <titlePart type="main">Die Schatzgräber.</titlePart>
    <titlePart type="sub">Posse in einem Aufzuge.</titlePart>
    <titlePart type="sub">Fortsetzung der beiden Billets.</titlePart>
  </docTitle>
  <docAuthor>Von G.L.P. Sievers.</docAuthor>
</titlePage>
```
Until now, we don't treat this appropriately in the frontend, see the example from above:

![layout-titlepage](https://user-images.githubusercontent.com/6539515/179990170-e62b509a-ec8a-4a30-96c1-dc5219c7d146.png)

Could we make CETEIcean brush up (i.e. increase) ```<docTitle>``` and ```<docAuthor>```?

**Comment by cmil** [comment]
The above PR implements some basic styling of the titlePage. It has been deployed to staging. See https://staging.dracor.org/ger/sievers-die-schatzgraeber#text.

@lehkost @markschwindt What do you think?

**Comment by lehkost** [comment]
This is great, thanks for taking this on, Carsten! It will encourage us to put titlePages into all documents that don't have one yet.

**Comment by markschwindt** [comment]
Looks good on “Die Schatzgräber”! The full text headers are indeed still very heterogeneous throughout different corpora.

**Comment by lehkost** [comment]
True, more homogeneity is needed, but this is already a larger step towards this goal…

**Comment by cmil** [comment]
@lehkost @markschwindt Do you have any immediate suggestions for improvements? Otherwise I would merge #240 and we can follow up later with a new issue.

**Comment by markschwindt** [comment]
I think it's good as it is at the moment. Let's merge and follow up later.
