### ISSUE TITLE
remove google fonts usage

### ISSUE THREAD

**Issue by mathias-goebel** [dracor-org/dracor-frontend#238]
google font usage is subject to legal warnings (Abmahnung).
possible solution:
- copy the resources to the frontend app or
- replace by well-known fonts

**Comment by cmil** [comment]
@mathias-goebel Thanks for the hint! I just [fixed this](https://github.com/dracor-org/dracor-frontend/commit/d6c8635cbfca49997ecb05449b36626b91aade96) and deployed a new frontend version at https://staging.dracor.org. @lehkost @markschwindt could you perhaps have a look to confirm that this can go to production.

**Comment by lehkost** [comment]
Cool, I just checked and didn't notice any difference in comparison to production…

**Comment by markschwindt** [comment]
Thank you so much for taking care of it! It looks and works perfectly.
