### ISSUE TITLE
Use consisting file names in the download tab

### ISSUE THREAD

**Issue by ingoboerner** [dracor-org/dracor-frontend#247]
The resulting filenames when downloading semantic layers in the download tab in most cases follow the pattern: `{id}.{playname}.-{layer slug}.{file format ending}` but there are some inconsistencies:
e.g. Network data: `{`${play.id}-${play.name}.graphml`}` (no dash no slug of semantic layer) https://github.com/dracor-org/dracor-frontend/blob/main/src/components/DownloadLinks.js#L37
TEI has a dot instead of a dash `${play.id}-${play.name}.tei.xml`, see https://github.com/dracor-org/dracor-frontend/blob/main/src/components/DownloadLinks.js#L146
I haven't checked all, but maybe we could use a consistent naming convention always including the semantic layer slug ?

**Comment by cmil** [comment]
@ingoboerner How about the following naming scheme:

- [play.id]-[play.name].network.{csv,gexf,graphml}
- [play.id]-[play.name].relations.{csv,gexf,graphml}
- [play.id]-[play.name].spoken.{json,txt}
- [play.id]-[play.name].stage.txt
- [play.id]-[play.name].stage-with-speakers.txt
- [play.id]-[play.name].cast.{json,csv}
- [play.id]-[play.name].tei.xml
- [play.id]-[play.name].rdf
