### ISSUE TITLE
Display of character names in Metrics tab flawed

### ISSUE THREAD

**Issue by lehkost** [dracor-org/dracor-frontend#38]
Check [this play](https://dracor.org/rus/blok-korol-na-ploschadi). The Metrics tab shows …

![voices-in-the-crowd-error](https://user-images.githubusercontent.com/6539515/46911106-d86f9e00-cf5a-11e8-80b7-15a291d9a546.png)

… showing both the Russian and English lable of the character with the highest degree. Maybe because it is a ```<personGrp>```, not a simple ```<person>```?

**Comment by cmil** [comment]
What the relevant XPath  does not expect is that the `<personGrp>` can have bot `<name>` and `<personName>` children as is the case here (https://github.com/dracor-org/rusdracor/blob/master/tei/blok-korol-na-ploschadi.xml#L121). Is this a mistake or valid markup?

**Comment by lehkost** [comment]
You're right, it was a markup error, fixed in https://github.com/dracor-org/rusdracor/commit/05b771c07c5942a2a3799568eecb525589171fbc.
