### ISSUE TITLE
Add "Network size" to overview (to add another sortability layer)

### ISSUE THREAD

**Issue by lehkost** [dracor-org/dracor-frontend#39]
In the overview ([GerDraCor](https://dracor.org/ger), [RusDraCor](https://dracor.org/rus), etc.), let's add the "Network size" per play as property to make it possible to sort plays by their network size, too. I suggest to place "Network size" between "Title" and "Written".

**Comment by cmil** [comment]
This has been implemented in 0.15.0 (and dracor-exist 0.27.0, dracor-metrics 0.1.0).
