### ISSUE TITLE
Render TEI documents

### ISSUE THREAD

**Issue by cmil** [dracor-org/dracor-frontend#4]
For each drama add a view providing the full text of the TEI document and highlighting its structure (headlines, stage directions etc.). The styling could be similar to the existing editor stylesheet used with the corpora (see https://github.com/dracor-org/rusdracor/tree/master/css) and should be designed to assist in proofreading the documents.

**Comment by lehkost** [comment]
Maybe use SADE for the job? https://wiki.de.dariah.eu/display/TextGrid/Publish+Tool+SADE

**Comment by cmil** [comment]
Or, maybe use https://github.com/DARIAH-DE/eXanore-viewer/blob/master/modules/customElements.xqm.

**Comment by lehkost** [comment]
If we have this implemented, we could link to the TEI documents from the [overview page](https://dracor.org/rus) like this (in the "Source" tab):

Wikisource
(TEI version)

Библиотека Максима Мошкова (lib.ru)
(TEI version)

Интернет-библиотека Алексея Комарова
(TEI version)

etc.

**Comment by cmil** [comment]
A first solution to render the TEI documents has been implemented in PR #28. It uses the [rusdracor `tei.css`](https://github.com/dracor-org/rusdracor/blob/master/css/tei.css) to render a styled version of the XML document.
