### ISSUE TITLE
YASGUI: implement link shortening service

### ISSUE THREAD

**Issue by ingoboerner** [dracor-org/dracor-frontend#43]
YASGUI can generate a share link. At the moment it's very bulky

https://dracor.org/sparql#query=PREFIX+rdf%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E%0APREFIX+rdfs%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0APREFIX+wdt%3A+%3Chttp%3A%2F%2Fwww.wikidata.org%2Fprop%2Fdirect%2F%3E%0APREFIX+wd%3A+%3Chttp%3A%2F%2Fwww.wikidata.org%2Fentity%2F%3E%0APREFIX+owl%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2002%2F07%2Fowl%23%3E%0APREFIX+dc%3A+%3Chttp%3A%2F%2Fpurl.org%2Fdc%2Felements%2F1.1%2F%3E%0APREFIX+dracon%3A+%3Chttp%3A%2F%2Fdracor.org%2Fontology%23%3E%0A++++++++%0A++++++++%0ASELECT+%3Fplay+%3FplayLabel+%3Fwikidata+%3FpremierePlace+%3Fcoords++WHERE+%7B%0A++%23+Get+all+plays+in+German+Drama+Corpus%0A++%3Fplay+dracon%3Ain_corpus+%3Chttps%3A%2F%2Fdracor.org%2Fger%3E+.%0A++%0A++%23+...+that+have+a+wikidata-id%0A++%3Fplay+owl%3AsameAs+%3Fwikidata+.%0A++%0A%0A++%23+use+wikidata+to+get+%22location+of+first+performance%22+%5BProperty+P4647%5D%0A++%0A%09%23+Federation%3A%0A++%09%09SERVICE+%3Chttps%3A%2F%2Fquery.wikidata.org%2Fsparql%3E+%7B%0A+%09%09%09%3Fwikidata+wdt%3AP4647+%3FpremierePlace+.%0A++%09%09%09%0A++++%09%23+if+availiable%2C+get+coordinates+of+this+place%0A++++%09%09OPTIONAL+%7B%3FpremierePlace+wdt%3AP625+%3Fcoords%7D%0A+%09%09%7D++%0A++%0A%7D+%0ALIMIT+200&contentTypeConstruct=text%2Fturtle&contentTypeSelect=application%2Fsparql-results%2Bxml&endpoint=https%3A%2F%2Fdracor.org%2Fapi%2Fsparql&requestMethod=POST&tabTitle=Locations+of+First+Perfomances&headers=%7B%22Content-Type%22%3A%22application%2Fx-www-form-urlencoded%22%7D&outputFormat=table

see YASGUI Documentation here: https://doc.yasgui.org/doc/

`urlShortener: string (default: null)
The URL via which to shorten URLs`

@lehkost, do you have any suggestions on which link-shortening service is OK-ish?

**Comment by lehkost** [comment]
Wikidata uses TinyURL, so I assume that's an okay one. But I'm open for suggestions.

**Comment by cmil** [comment]
We cannot use TinyURL directly here, since they don't set the required CORS headers. We would have to proxy the requests or setup [YASGUI.server](https://github.com/OpenTriply/YASGUI.server).
