### ISSUE TITLE
Combine person+personGrp in corpus metrics on DraCor frontpage

### ISSUE THREAD

**Issue by lehkost** [dracor-org/dracor-frontend#55]
So far, only ```<person>``` is counted for each corpus on [DraCor frontpage](https://dracor.org/).

Proposition: Display combined ```person+personGrp``` counts including counts for *male* and *female* characters/groups.

**Comment by cmil** [comment]
@lehkost `personGrp`s should now be included in the count. Please test.

**Comment by lehkost** [comment]
Yes, it looks like it's included now, thanks. To be fully transparent, shouldn't we write ```person+personGrp``` in front of the number, though?
