### ISSUE TITLE
Reorganise pages for plays (preparation for web design)

### ISSUE THREAD

**Issue by lehkost** [dracor-org/dracor-frontend#60]
In preparation of the work on the web design, let us reorganise the pages for plays.

Example: https://dracor.org/ger/lessing-emilia-galotti

* Enrich Metadata (author, title, etc.) and put it in a box on the left (instead of reaching into the right part of the screen), letting the main window for networks, speech distribution etc. reach up to the top.
* Metadata to include (using the example):
  * Lessing, Gotthold Ephraim (pnd)
  * Emilia Galotti (Wikidata ID, DraCor ID)
  * Ein Trauerspiel in fünf Aufzügen
  * [staged] 1772 [printed] 1772 [using Font Awesome icons]
  * Source: TextGrid Repository
* At the same time, add a new function for the main window in the right part of the screen to show our TEI version of the text, for the time being with our ugly CSS, we can make it look nicer later. (The actual text of each play should be displayable on the pages dedicated to each plays.)

All the following boxes on the left should be collapsed (only showing the title if not clicked on) to win space. By clicking on them, they expand, revealing their information:

* Download
  * network data: CSV · GEXF
  * spoken-text: TXT
  * spoken-text-by-character: JSON
  * stage-directions: TXT

* Network Metrics:
  * [keep as is, but show it collapsed in the beginning]

* Cast list (in order of appearance)
  * [keep as is, but show it collapsed in the beginning]

**Comment by cmil** [comment]
The requested changes have been made in the above PR and have already been deployed to https://dracor.org. @lehkost please have a look. If ok, merging the pull request would also close this issue.
