### ISSUE TITLE
Add new tab "Relations"

### ISSUE THREAD

**Issue by lehkost** [dracor-org/dracor-frontend#69]
After dracor-org/dracor-api#90 is implemented, we can add a new tab to the frontend called "Relations" (only if relation information is available for a play, of course). Just like the "Network" tab, it will display the relation data as network (via sigma.js again). These relation networks will be much smaller and will have no weight information, but "relation" information instead.

The idea is to label the edges with the corresponding of the 7 types of relation as documented in the [GerDraCor README](https://github.com/dracor-org/gerdracor#character-relations). Each edge type could also get a different colour. The 4 relation types that are directed should also have an arrow pointing into the right direction. 

The presentation of relations as tab on the website will also allow us to hunt for bugs in the TEI encoding.

**Comment by cmil** [comment]
A first version of the relations tab is now on staging. See for instance https://staging.dracor.org/rus/griboyedov-gore-ot-uma#relations.
