### ISSUE TITLE
Add widget with scenes/acts in full-text mode

### ISSUE THREAD

**Issue by lehkost** [dracor-org/dracor-frontend#76]
This is meant for the full-text mode in the new web design (to make the view context-sensitive). The proposition is to add to the clickable list all ```<div><head>``` of the segments we use for the extraction of network data. Usually this should look like this:

* Erster Aufzug
  * Erster Aufzug
  * Zweiter Auftritt
* Zweiter Aufzug
  * Erster Aufzug
  * [etc.]

Not sure if we need to add anchors for this in the original documents?

In addition, we could also add a (non-clickable) list of all speakers per scene to facilitate the navigation through the full text.

**Comment by lehkost** [comment]
To feature jump-to anchors, we will have to adapt our implementation of [CETEIcean](https://github.com/TEIC/CETEIcean). For the time being it would be enough to just list the strings within ```<head>``` elements before tackling the CETEIcean issue.

**Comment by cmil** [comment]
This has sufficiently be implemented in the above PR. There is a now #200 to take care of linking the segments list to the full text.
