### ISSUE TITLE
Display DraCor and eXist version in the footer of the frontpage

### ISSUE THREAD

**Issue by lehkost** [dracor-org/dracor-frontend#80]
To make transparent that the DraCor website runs on our API and eXist, we should display both version numbers (via https://dracor.org/api/info) at the bottom of the frontpage at https://dracor.org/

Since we're still in the 0.x area, we can also skip the "beta" version, I think.

Suggestion: "dracor.org runs on DraCor API 0.69.3 using eXist-db 5.2.0. ~~Last engine update dd mm yy.~~"

**Comment by markschwindt** [comment]
Pushed footer updates to PR #86. Please review.
