### ISSUE TITLE
Indicate current corpus in play info page

### ISSUE THREAD

**Issue by cmil** [dracor-org/dracor-frontend#84]
On the play info page there should be some hint which corpus the play belongs to.

**Comment by markschwindt** [comment]
I suggest showing the short corpus name (e.g. GerDraCor) inline with dashboard tabs floating right. 

`<Link to={`/${m.name}`}>
            <h1><span>{m.name}</span>DraCor</h1>
            </Link>`

The snippet from Metrics.js would be perfect for it.

**Comment by markschwindt** [comment]
Solved in #110
