### ISSUE TITLE
Display more network metrics per play

### ISSUE THREAD

**Issue by lehkost** [dracor-org/dracor-frontend#9]
- [x] Segments (already in place).
- [x] Density (already in place). [The density of a network is the proportion of edges relative to the total number of possible edges.]
- [x] Network size (= number of characters).
- [x] Diameter.
- [x] Clustering coefficient.
- [x] Average path length.
- [x] Average Degree.
- [x] Maximum degree (and name of the character with maximum degree).

**Comment by cmil** [comment]
Most of the metrics have been implemented with PR #19 (which is also what's currently deployed on [dracor.org](https://dracor.org)).

I'm not quite sure about the _average degree_. According to https://en.wikipedia.org/wiki/Network_science#Average_degree it seems to be something else than the average of the degrees of all nodes.

**Comment by lehkost** [comment]
re *average degree*: it should be exactly this. in the article you quote they use the formula (2*E)/N, which is another way of putting it. the rest they write is on random networks, which should not concern us for now.

**Comment by cmil** [comment]
I added the average degree and merged PR #19.
