### ISSUE TITLE
Put downloads in a new "Data" tab on play info page

### ISSUE THREAD

**Issue by cmil** [dracor-org/dracor-frontend#97]
While the design of the download links in the head section of the play info page is pretty, IMO it is struggling a bit with the lack of space there. We could consider to add a new "Data" tab where these links could be presented in a more lavish layout, possible descriptions and with room to add more formats in the future.

**Comment by lehkost** [comment]
Proposition for a more descriptive download page (including more things to download now that we have more space):

* Network data:
  * Co-occurrence network:
    * CSV
    * GEXF (preferred format for Gephi)
    * GraphML (preferred format for Cytoscape)
  * Relation data:
    * CSV
    * GEXF
* Full text:
  * TEI
* List of characters with some precalculated data:
  * CSV
  * JSON
* Spoken text only (without markup):
  * TXT
* Spoken text by character:
  * JSON
* Stage directions only:
  * Without speaker names:
    * TXT
  * Including speaker names:
    * TXT
* Linked data:
  * RDF
