### ISSUE TITLE
Move source information to new play info tab

### ISSUE THREAD

**Issue by cmil** [dracor-org/dracor-frontend#98]
The source information in the head section of the play info page can, for some plays, take quite a huge amount  of space. While certainly important, one could argue it's not the most sought after information about a play on dracor.org, and thus does not need such a prominent place. We could consider moving it to a separate tab.

This would together with #97 would also free some space that might be better used for more prominent author information, e.g. #10.

**Comment by lehkost** [comment]
I agree. The three "year" information boxes and Wikidata ID for the play could go below or next to the play's title. The "Source" tab could then hold the following information (just a draft as base for discussion):

---

**Perma link to this DraCor item:**
[ger000088](https://dracor.org/id/ger000088) {button: COPY}

**Digitised text provided through:**
TextGrid Repository ([http://www.textgridrep.org/textgrid:rksp.0](http://www.textgridrep.org/textgrid:rksp.0))

**License:** full text is Public Domain. DraCor file and DraCor-specific markup under CC 0.

**Print Source:**
Gotthold Ephraim Lessing: Werke. Herausgegeben von Herbert G. Göpfert in Zusammenarbeit mit Karl Eibl, Helmut Göbel, Karl S. Guthke, Gerd Hillen, Albert von Schirmding und Jörg Schönert, Band 1–8, München: Hanser, 1970 ff.

(In case of error corrections, the DraCor file is aligned with the print source.)

**DraCor TEI file on GitHub:**
[https://github.com/dracor-org/gerdracor/blob/master/tei/lessing-emilia-galotti.xml](https://github.com/dracor-org/gerdracor/blob/master/tei/lessing-emilia-galotti.xml)

---

**Comment by cmil** [comment]
We decided to put the source information into the description of the full text tab. See #127.
